//Get Suggested
export const SUGGESTED_FETCHED = 'SUGGESTED_FETCHED';
export const SUGGESTED_FETCHED_SUCCESS = 'SUGGESTED_FETCHED_SUCCESS';
export const SUGGESTED_FETCHED_FAILURE = 'SUGGESTED_FETCHED_FAILURE';

//Add Suggested
export const ADD_SUGGESTED = 'ADD_SUGGESTED';
export const ADD_SUGGESTED_SUCCESS = 'ADD_SUGGESTED_SUCCESS';
export const ADD_SUGGESTED_FAILURE = 'ADD_SUGGESTED_FAILURE';
