//Get Suggested
export const SUGGESTED_FETCHED = 'SUGGESTED_FETCHED';
export const SUGGESTED_FETCHED_SUCCESS = 'SUGGESTED_FETCHED_SUCCESS';
export const SUGGESTED_FETCHED_FAILURE = 'SUGGESTED_FETCHED_FAILURE';

//Get Starred
export const STARRED_FETCHED = 'STARRED_FETCHED';
export const STARRED_FETCHED_SUCCESS = 'STARRED_FETCHED_SUCCESS';
export const STARRED_FETCHED_FAILURE = 'STARRED_FETCHED_FAILURE';

//Add Suggested
export const ADD_SUGGESTED = 'ADD_SUGGESTED';
export const ADD_SUGGESTED_SUCCESS = 'ADD_SUGGESTED_SUCCESS';
export const ADD_SUGGESTED_FAILURE = 'ADD_SUGGESTED_FAILURE';

//Delete Suggested
export const DELETE_STARRED = 'DELETE_STARRED';
export const DELETE_STARRED_SUCCESS = 'DELETE_STARRED_SUCCESS';
export const DELETE_STARRED_FAILURE = 'DELETE_STARRED_FAILURE';

//Sort Influencers
export const CHANGE_ORDER = 'CHANGE_ORDER';
export const NAME_A_TO_Z = 'NAME_A_TO_Z';
export const NAME_Z_TO_A = 'NAME_Z_TO_A';
export const FOLLOWERS_HIGH_TO_LOW = 'FOLLOWERS_HIGH_TO_LOW';
export const FOLLOWERS_LOW_TO_HIGH = 'FOLLOWERS_LOW_TO_HIGH';
export const ENGAGEMENT_HIGH_TO_LOW = 'ENGAGEMENT_HIGH_TO_LOW';
export const ENGAGEMENT_LOW_TO_HIGH = 'ENGAGEMENT_LOW_TO_HIGH';
export const DEFAULT_ORDER = 'DEFAULT_ORDER';
